/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  4202: {
    LinkContract: {
      address: "0x50fA36b67daFdc52BDCF6077545b6E4Aa6f9b4db",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "productName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "complaint",
              type: "string",
            },
          ],
          name: "BuyerRefunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "lodger",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "product",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "complaint",
              type: "string",
            },
          ],
          name: "ComplaintLodged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "lodger",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "arbitrator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "product",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "judgement",
              type: "string",
            },
          ],
          name: "ComplaintResolved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "vendor",
              type: "address",
            },
          ],
          name: "CustomerRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "vendor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "id",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
          ],
          name: "TaskAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "vendor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "commission",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "productName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "id",
              type: "bytes32",
            },
          ],
          name: "TaskPaid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "vendor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "time",
              type: "uint256",
            },
          ],
          name: "VendorFlagged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "vendor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "VendorPaid",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "vendor",
              type: "address",
            },
          ],
          name: "VendorRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "vendor",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "time",
              type: "uint256",
            },
          ],
          name: "VendorUnflagged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "when",
              type: "uint256",
            },
          ],
          name: "Withdrawal",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "email",
              type: "string",
            },
            {
              internalType: "string",
              name: "phoneNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "homeAddress",
              type: "string",
            },
            {
              internalType: "string",
              name: "role",
              type: "string",
            },
            {
              internalType: "string",
              name: "picture",
              type: "string",
            },
          ],
          name: "RegisterCustomer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "email",
              type: "string",
            },
            {
              internalType: "string",
              name: "phoneNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "homeAddress",
              type: "string",
            },
            {
              internalType: "string",
              name: "role",
              type: "string",
            },
            {
              internalType: "string",
              name: "picture",
              type: "string",
            },
            {
              internalType: "string",
              name: "service",
              type: "string",
            },
            {
              internalType: "string",
              name: "file1",
              type: "string",
            },
            {
              internalType: "string",
              name: "file2",
              type: "string",
            },
            {
              internalType: "string",
              name: "file3",
              type: "string",
            },
          ],
          name: "RegisterVendor",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "addArbitrator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "vendor",
              type: "address",
            },
          ],
          name: "addTask",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "allVendors",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "commission_rate",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "customer_C",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "customers",
          outputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "email",
              type: "string",
            },
            {
              internalType: "string",
              name: "phoneNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "homeAddress",
              type: "string",
            },
            {
              internalType: "string",
              name: "role",
              type: "string",
            },
            {
              internalType: "string",
              name: "picture",
              type: "string",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "str1",
              type: "string",
            },
            {
              internalType: "address",
              name: "str2",
              type: "address",
            },
          ],
          name: "generateID",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllTasks",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "id",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "price",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "vendor",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "customer",
                  type: "address",
                },
                {
                  internalType: "bool",
                  name: "completed",
                  type: "bool",
                },
              ],
              internalType: "struct LinkContract.Task[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllVendors",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "id",
              type: "bytes32",
            },
          ],
          name: "getTask",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "id",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "description",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "price",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "vendor",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "customer",
                  type: "address",
                },
                {
                  internalType: "bool",
                  name: "completed",
                  type: "bool",
                },
              ],
              internalType: "struct LinkContract.Task",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "product_name",
              type: "string",
            },
            {
              internalType: "string",
              name: "complaint",
              type: "string",
            },
          ],
          name: "lodgeComplaint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
          ],
          name: "payForTask",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "paySeller",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "profiles",
          outputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "email",
              type: "string",
            },
            {
              internalType: "string",
              name: "phoneNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "homeAddress",
              type: "string",
            },
            {
              internalType: "string",
              name: "role",
              type: "string",
            },
            {
              internalType: "string",
              name: "picture",
              type: "string",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              internalType: "string",
              name: "judgement",
              type: "string",
            },
          ],
          name: "resolveComplaint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              internalType: "string",
              name: "judgement",
              type: "string",
            },
          ],
          name: "returnBuyerFunds",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_rate",
              type: "uint256",
            },
          ],
          name: "setCommissionRate",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "taskList",
          outputs: [
            {
              internalType: "bytes32",
              name: "id",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "description",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "vendor",
              type: "address",
            },
            {
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              internalType: "bool",
              name: "completed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "vendor_C",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "vendors",
          outputs: [
            {
              internalType: "string",
              name: "service",
              type: "string",
            },
            {
              internalType: "string",
              name: "file1",
              type: "string",
            },
            {
              internalType: "string",
              name: "file2",
              type: "string",
            },
            {
              internalType: "string",
              name: "file3",
              type: "string",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "totalMoney",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "flagged",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "withdrawCommission",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
